# This provides us with GCC binary support so we can run bash
language: generic

sudo: required

script:
  - ./build.sh
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./scripts/aptRepoUpdater.sh; fi'

before_deploy:
  - export image_name="`echo *.iso`"
  - cat *.iso > "/home/travis/${image_name}"

notifications:
  slack: fossasia:3pMkQrSogvEMfnu9aJDW2ZYC

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: "u4Ixnn+aq84c+ijJOtvUpZa7wHL8Znk8qJbT9Skwbd+hHDxyqmsK+lOsCldTLs3BSiGoxG3ga1CGrfmV2BDW90IZeXhwuy+OpMSGIPuD1amqk1CJmNOVinbQcO1VlP10804WCcCZjl1pLJvgXOKjC5SVYy7WpEmHWGn2/+0dHTKWFeclZaMIosdepkEai1Bz9enWesGz3NKkk6w+jHukBuI1KzgfcP2A5kb6k1+uT9YY+BK9eSogvDh6L+CPHs4pkAodSMP/9KTx/5u7XT+cPPd50gNm4M9YY5lTbgt4h2IL0JOPfye7X98NkSS616PwcLEe4vjGHgI1EtC1lFEbgz2iHdyo/84GpElRhWcku+pLw/qmnjVx9owTc7ze1ovPUSVCbNP0w4kuqYg8uYQWMVs12l/YSQ0lzC2dvHQbeeTLXuQlFPg9nBJIjLe8W+6vsu5lUdPwdQCd2hwgkwbcnRZgSLbHdXy0G8sEcof4hW796YYavq7NtgwpCarp0dxxAMKKszvn6DawbFGR3nFNnKa5tUXZSOnBWaBCMayvV8ToJDpbSk8OQENSyguNmWe0VYb92Qe1wtVda4AcAAt+AbN/WFpdvYylb5NVmz9Zb36UfpCOQczkgNu2tNQvjR7Rdrt77gkDGGwEA3kwB8oq3LgWULKzPDN2bqSaVypvP0A="
    file_glob: true # http://stackoverflow.com/a/28579635/1320237
    file: "/home/travis/${image_name}"
    on:
      branch: master
